name: Build Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
env:
  ECR_REPOSITORY: "vprofile-appimage"
permissions:
  contents: read
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Maven Build
        run: mvn install

      - name: Upload The Artifact (War)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if the build fails
        if: failure()
        run: echo "Build failed"

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Run test on Main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: Checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: Run tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests and code analysis"

  Security-Scan:
    runs-on: ubuntu-24.04
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: os,library
          output: trivy.results.json
      - name: Upload The Artifact (War)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy.results.json

  Build-And-Publish:
    name: Build-And-Publish
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    needs: [Build, Testing, Security-Scan]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        env:
          ECR_REGISTERY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTERY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTERY/$ECR_REPOSITORY:$IMAGE_TAG
